### PR TITLE
minor tweaks/improvements to climatology and util functions; extended tests

### PR DESCRIPTION
**Pull request by matt-long**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs (you can delete this text from the final description, this is
just a guideline):

- [ ] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [CHANGELOG.rst](https://github.com/NCAR/esmlab/blob/master/CHANGELOG.rst) for details.
- [ ] Include documentation when adding new features.
- [x] Include new tests or update existing tests when applicable.

Working with the climatology function has uncovered some shortcomings. This pull request addresses some of these.

### CODE REVIEW

**Comment by andersy005** [comment]
@matt-long, is this PR ready yet?

**Comment by matt-long** [comment]
Ready!

**Comment by matt-long** [comment]
@klindsay28: I dropped the `time_bound` variable because it was not being computed correctly and was therefore wrong. You are absolutely correct, however: we should include a correct `time_bound` variable and associated `bounds` attribute in the output. 

Do you have suggestion for how it should be computed?  I can try to look at this today.

**Comment by klindsay28** [comment]
The following might be a step in the correct direction:

> tb_out_lo = dset[tb_name][:,0].groupby(time_dot_year).min(dim=time_coord_name).rename({"year": time_coord_name})
tb_out_hi = dset[tb_name][:,1].groupby(time_dot_year).max(dim=time_coord_name).rename({"year": time_coord_name})
d2_name = dset[tb_name].dims[1]
tb_out = xr.concat((tb_out_lo, tb_out_hi), dim=d2_name)


(Sorry for the long lines. I couldn't figure out how to get line wrapping with 'insert a quote' or 'insert code' to work.)

**Comment by matt-long** [comment]
@klindsay28, thanks, that works. I have implemented. Testing now and hope to have a PR shortly. 
cc @andersy005

**Pull request merged**
