### PR TITLE
Code Refactoring

### LINKED ISSUE #36: rename `grid_vars` to `static_vars`
`grid_vars` is somewhat confusing; these are variables that don't change as a function of time, but they do not necessarily describe aspects of the grid.  

A better name might be `static_vars`.

We are relying on the fact that a coordinate named `time` is in the dataset. This is obviously a bit fragile. Alternatives would be detect `unlimited_dim` (also fragile), have a user-specified fallback, or give up and don't do the operations that rely on `static_vars`. Actually, this reliance on `time` is pervasive and perhaps a bigger issue.

### PR DESCRIPTION
**Pull request by andersy005**
- Refactor utils
- Closes #36 
- Partially address #39

### CODE REVIEW

**Comment by kmpaul** [comment]
You can check if a dimension is unlimited with a netCDF4 method (unlimited? Or is_unlimited?).  However, if there is more than 1, you still don’t know which one is “time”.

It is a CF convention to can the time coordinate “time”, and I would assume that. There is no other way.

**Comment by klindsay28** [comment]
See https://github.com/NCAR/esmlab/issues/39#issuecomment-459718549 for a suggestion on identifying the time axis.

**Comment by kmpaul** [comment]
That method is fine if there is only 1 dimension with proper time-like CF units. However, there are NetCDF files with 2 time dimensions. So that will not uniquely identify the one you want. 

My advise is to assume “time” but supply the user with an optional argument to set it to what they want.

**Comment by kmpaul** [comment]
Or, you can try any of the other options (or a combination of them) first, and if they do not find a unique time coordinate, then throw an exception. And let a user-supplied optional argument override.

**Comment by andersy005** [comment]
@matt-long, This is ready for review. And if it looks good to you, feel free to merge it. 

I should point out that this partially addresses #39. Because the discussion in that issue seems to be ongoing, I think it is better to dedicate a separate PR that tries to (fully) address that issue for another time.

**Pull request merged**
