### PR TITLE
Add xarray alignment option

### LINKED ISSUE #46: Trigger errors when coordinates don't match
I have encountered issues operating on files with lossy compression applied to coordinates. In these cases, `xarray` can do the wrong thing when applying its logic for coordinate alignment. 

If the coordinates don't match, it takes the 'inner' set by default:
```
>>> da1 = xr.DataArray(np.ones(4), dims=('x'), coords={'x': [1.,2.,3.,4.]})
>>> da2 = xr.DataArray(2*np.ones(4), dims=('x'), coords={'x': [1.,2.,3.,4.01]})
>>> da1 * da2
<xarray.DataArray (x: 3)>
array([2., 2., 2.])
Coordinates:
  * x        (x) float64 1.0 2.0 3.0
```
This is seldom desired in the applications I am familiar with.

We could therefore wrap all instances where we are relying on automatic alignment in a context manager as follows.
```
with xr.set_options(arithmetic_join='exact'):
   dao = da1 * da2

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-4bb80efa7a54> in <module>()
      9 with xr.set_options(arithmetic_join='exact'):
---> 10     dao = da1 * da2

/glade/work/mclong/miniconda3/envs/py3/lib/python3.6/site-packages/xarray/core/dataarray.py in func(self, other)
   1965                 align_type = (OPTIONS['arithmetic_join']
   1966                               if join is None else join)
-> 1967                 self, other = align(self, other, join=align_type, copy=False)
   1968             other_variable = getattr(other, 'variable', other)
   1969             other_coords = getattr(other, 'coords', None)

/glade/work/mclong/miniconda3/envs/py3/lib/python3.6/site-packages/xarray/core/alignment.py in align(*objects, **kwargs)
    130                     raise ValueError(
    131                         'indexes along dimension {!r} are not equal'
--> 132                         .format(dim))
    133                 index = joiner(matching_indexes)
    134                 joined_indexes[dim] = index

ValueError: indexes along dimension 'x' are not equal
```

### PR DESCRIPTION
**Pull request by andersy005**
- Closes #46

### CODE REVIEW

**Comment by andersy005** [comment]
@matt-long, Are there any undesired ramifications if we were to set `xr.set_options(arithmetic_join="exact")` as global option instead of doing this within a context manager?

**Comment by matt-long** [comment]
I would not expect any issues from a global setting.

**Comment by matt-long** [comment]
@andersy005, I think you can fix these errors by changing lines 256-262 in `climatology.py` to the following.
```python
    ones = (
        dset.drop(static_variables)
        .where(dset.drop(static_variables).isnull())
        .fillna(1.0)
        .where(dset.drop(static_variables).notnull())
        .fillna(0.0)
    )
```
It was good to enable this option globally!

**Comment by andersy005** [comment]
@matt-long, Thank you for taking care of this!

**Pull request merged**
