### PR TITLE
climatology function updates

### LINKED ISSUE #32: compute_time_var should accept year offset and should not require multiple of 12
Add new argument to `compute_time_var`: `year_offset=None`

Then after computing `date`, add something like the following

```
    if year_offset is not None and ~np.isnan(year_offset):
        date += cftime.date2num(datetime(int(year_offset),1,1),
                                       ds.time.attrs['units'],
                                       ds.time.attrs['calendar'])
```

Also, I think we should remove this check:
```
if len(date) % 12 != 0:
        raise ValueError("Time axis not evenly divisible by 12!")
```

### PR DESCRIPTION
**Pull request by matt-long**
- [x] closes #32
 - [x ] tests added / passed
 - [x] docs reflect changes
 - [ ] passes ``flake8 esmlab tests docs``
 - [ ] entry in changelog.rst

Several modification to climatology functions and utils to ensure proper return types, etc.

### CODE REVIEW

**Comment by andersy005** [comment]
@matt-long, the failure is due to code styling.. To resolve this:

From the root directory of this project run the following:

`$ pip install pre-commit`
`$ pre-commit install`
pre-commit hooks specified in (https://github.com/NCAR/esmlab/blob/master/.pre-commit-config.yaml) will run every time you are about to commit code

**Comment by matt-long** [comment]
Thanks...I think I am close to having it all working...but unfortunately Cheyenne is stalling out on me.

**Comment by matt-long** [comment]
@andersy005 so now the codecov checks are failing. Is this because I introduced new if/else branch points in the code?

**Comment by andersy005** [comment]
Codecov is complaining because the code coverage decreased. However, this is not a big deal :)

**Comment by andersy005** [comment]
@matt-long, Are you still working on this PR? (Let me known whether it's ready to be merged in master)

**Comment by matt-long** [comment]
@andersy005  go ahead and merge!

**Comment by andersy005** [comment]
Thank you, @matt-long!

**Pull request merged**
