### PR TITLE
Add a new function to compute monthly averages

### PR DESCRIPTION
**Pull request by alperaltuntas**
Checklist

- [x] Enable and install [pre-commit](https://pre-commit.com/) to ensure style-guides and code checks are followed.
- [x] Target **master** for bugfixes and doc changes.
- [x] Target **devel** for new features or functionality changes.
- [ ] Include documentation when adding new features.
- [ ] Include new tests or update existing tests when applicable.

Fixes: #55 

Adds a new function to compute monthly averages from a given dataset that has more frequent data, e.g., 5 day means.

Summary of what the function does:
- First, the input dataset gets "grouped by" time_bound months. (The time_bound gets expanded, i.e., gets reshaped to be 1-dimensional for the purpose of grouping. All the DataArrays in the dataset are reshaped accordingly.)
- Then, a local function "weighted_monthly_mean" is applied to each group: Weights get computed for each chunk (e.g. 5-day) of each group (month), by taking into account how much of the chunk falls within the group.
- Finally, time and time_bound get corrected for each group (month).

Note 1: Parts of the function may be (unnecessarily) complicated, so a code review may perhaps be helpful.
Note 2: The existing monthly climatology function (compute_mon_climatology) may be rewritten to call this new function (compute_mon_averages) to compute the averages, and then to compute *the correct* climatology (pretty easily).
Note 3: This is a draft pull request for now, since I haven't tested it thoroughly. Let me know any issues you notice/encounter.

To test this function, you may run the following on cheyenne:
```
from glob import glob
import xarray as xr
import esmlab

files = sorted(glob('/glade/scratch/altuntas/archive/g.e20.GIAF.T62_g37.test_d2m.001/ocn/hist/g.e20.GIAF.T62_g37.test_d2m.001.pop.h.0001-1*.nc'))
ds = xr.open_mfdataset(files, decode_times=False, decode_coords=False)
ds_monclim = esmlab.climatology.compute_mon_averages(ds)
ds_monclim.to_netcdf("test.nc")
```

### CODE REVIEW

**Comment by matt-long** [comment]
@alperaltuntas, have you looked into @andersy005's suggestion? I think the new resample capability on CFTimeIndex could greatly simplify this type of application.

**Comment by alperaltuntas** [comment]
@matt-long, @andersy005, I'll look into it. Thanks.

**Comment by matt-long** [comment]
One think to keep in mind is an ability to correctly handled missing values that vary in time.

**Comment by andersy005** [comment]
@alperaltuntas, I am sorry I deleted the `devel` without making sure that there were no open pull requests. When you get time, please open a PR against the master branch

**Pull request closed without merging**
